<?php /* views/estilos/atenderServiciosEstilo.php */ ?>
<style>
:root{
  --ev-as-green-900:#0F592F;--ev-as-green:#16A34A;--ev-as-green-050:#F0FDF4;
  --ev-as-orange:#EA7C12;--ev-as-orange-dark:#C46B05;--ev-as-orange-050:#FFF7ED;
  --ev-as-red:#DC2626;--ev-as-red-050:#FEF2F2;--ev-as-blue:#2563EB;--ev-as-blue-050:#EFF6FF;
  --ev-as-text:#111827;--ev-as-muted:#64748B;--ev-as-border:#E5E7EB;
  --ev-as-shadow:0 16px 40px rgba(15,23,42,.08);
}
.ev-as-page{padding:16px 16px 30px;color:var(--ev-as-text)}
.ev-as-hero,.ev-as-panel{background:#fff;border:1px solid rgba(148,163,184,.18);border-radius:25px;box-shadow:var(--ev-as-shadow);overflow:hidden}
.ev-as-hero{padding:20px;display:flex;align-items:center;justify-content:space-between;gap:18px;background:radial-gradient(circle at 88% 12%,rgba(22,163,74,.13),transparent 34%),radial-gradient(circle at 12% 88%,rgba(234,124,18,.11),transparent 30%),linear-gradient(135deg,#fff,#f7fcf9)}
.ev-as-hero-copy{display:flex;align-items:flex-start;gap:14px;min-width:0}.ev-as-icon{width:56px;height:56px;display:grid;place-items:center;border-radius:19px;background:#fff;border:1px solid rgba(22,163,74,.22);color:var(--ev-as-green-900);font-size:1.35rem;box-shadow:0 12px 24px rgba(15,23,42,.08);flex:0 0 auto}
.ev-as-kicker{font-size:.73rem;letter-spacing:.14em;font-weight:900;color:var(--ev-as-orange);margin-bottom:4px}.ev-as-hero h2{margin:0;color:var(--ev-as-green-900);font-size:2rem;font-weight:950;letter-spacing:-.035em}.ev-as-hero p{margin:5px 0 0;color:var(--ev-as-muted);max-width:780px;font-size:.93rem;line-height:1.5}
.ev-as-refresh{border:0;border-radius:999px;background:linear-gradient(135deg,var(--ev-as-orange),#F59E0B);color:#fff;font-weight:900;padding:.75rem 1.05rem;box-shadow:0 12px 25px rgba(234,124,18,.25);white-space:nowrap}.ev-as-refresh:hover{color:#fff;transform:translateY(-1px)}
.ev-as-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.ev-as-summary article{position:relative;background:#fff;border:1px solid rgba(148,163,184,.17);border-radius:21px;padding:17px 18px;box-shadow:0 10px 26px rgba(15,23,42,.06);overflow:hidden}.ev-as-summary article:after{content:"";position:absolute;left:0;right:0;bottom:0;height:4px;background:linear-gradient(90deg,var(--ev-as-green),var(--ev-as-orange));opacity:.35}.ev-as-summary span{display:block;color:var(--ev-as-muted);font-size:.78rem;font-weight:850}.ev-as-summary strong{display:block;margin:5px 0;color:var(--ev-as-green-900);font-size:1.75rem;line-height:1;font-weight:950}.ev-as-summary small{color:#94A3B8;font-size:.74rem;font-weight:750}
.ev-as-panel-head{padding:18px;border-bottom:1px solid var(--ev-as-border);display:flex;align-items:flex-start;justify-content:space-between;gap:16px;flex-wrap:wrap}.ev-as-panel-head h5{margin:0 0 4px;color:var(--ev-as-green-900);font-weight:950}.ev-as-panel-head p{margin:0;color:var(--ev-as-muted);font-size:.87rem;line-height:1.45;max-width:710px}.ev-as-filters{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.ev-as-tabs{display:flex;gap:6px;padding:6px;border:1px solid var(--ev-as-border);border-radius:999px;background:#F8FAFC}.ev-as-tab{border:0;border-radius:999px;background:transparent;color:#475569;font-size:.8rem;font-weight:900;padding:8px 12px}.ev-as-tab.active{background:#fff;color:var(--ev-as-green-900);box-shadow:0 5px 14px rgba(15,23,42,.08)}
.ev-as-search{height:42px;display:flex;align-items:center;gap:8px;border:1px solid var(--ev-as-border);border-radius:14px;padding:0 12px;background:#fff;color:#94A3B8}.ev-as-search:focus-within{border-color:rgba(22,163,74,.5);box-shadow:0 0 0 4px rgba(22,163,74,.1)}.ev-as-search input{border:0;outline:0;min-width:230px;color:var(--ev-as-text);font-size:.84rem;background:transparent}
.ev-as-panel-body{padding:18px;background:linear-gradient(180deg,#FCFDFC,#F8FAF9)}.ev-as-list{display:grid;gap:13px}.ev-as-case{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:16px;align-items:center;background:#fff;border:1px solid rgba(148,163,184,.18);border-radius:20px;padding:16px;box-shadow:0 8px 22px rgba(15,23,42,.05);transition:.16s ease}.ev-as-case:hover{transform:translateY(-1px);border-color:rgba(22,163,74,.28);box-shadow:0 16px 30px rgba(15,23,42,.08)}.ev-as-case-main{min-width:0}.ev-as-case-top{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:7px}.ev-as-case-id{font-size:.72rem;font-weight:950;color:var(--ev-as-orange);letter-spacing:.06em}.ev-as-case-title{font-size:1rem;font-weight:950;color:var(--ev-as-green-900)}.ev-as-badge{display:inline-flex;align-items:center;border-radius:999px;padding:5px 9px;font-size:.7rem;font-weight:950}.ev-as-badge-open{background:var(--ev-as-red-050);color:#991B1B;border:1px solid #FECACA}.ev-as-badge-wait{background:var(--ev-as-orange-050);color:#9A3412;border:1px solid #FED7AA}.ev-as-badge-done{background:var(--ev-as-green-050);color:#166534;border:1px solid #BBF7D0}.ev-as-case-meta{display:flex;flex-wrap:wrap;gap:8px 14px;color:var(--ev-as-muted);font-size:.78rem;font-weight:750}.ev-as-case-meta span{display:inline-flex;align-items:center;gap:5px}.ev-as-case-desc{margin-top:9px;color:#475569;font-size:.84rem;line-height:1.45;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.ev-as-btn-detail{border:0;border-radius:14px;background:linear-gradient(135deg,var(--ev-as-green-900),#15803D);color:#fff;font-weight:900;padding:.72rem 1rem;box-shadow:0 10px 22px rgba(15,89,47,.18)}.ev-as-btn-detail:hover{color:#fff;transform:translateY(-1px)}
.ev-as-loading,.ev-as-empty{min-height:150px;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:10px;color:var(--ev-as-muted)}.ev-as-loading span{width:42px;height:42px;border-radius:50%;border:4px solid rgba(22,163,74,.15);border-top-color:var(--ev-as-green-900);animation:evAsSpin .8s linear infinite}@keyframes evAsSpin{to{transform:rotate(360deg)}}.ev-as-loading p{margin:0;font-weight:800}.ev-as-empty i{font-size:2rem;color:var(--ev-as-green)}.ev-as-empty strong{font-size:.95rem}.ev-as-alert{margin-bottom:14px;padding:12px 14px;border-radius:15px;background:var(--ev-as-red-050);border:1px solid #FECACA;color:#991B1B;font-weight:800}
.ev-as-detail{display:grid;gap:13px;text-align:left}.ev-as-detail-head{display:grid;grid-template-columns:90px minmax(0,1fr);gap:13px}.ev-as-detail-head img{width:90px;height:90px;object-fit:cover;border-radius:18px;background:#F1F5F9}.ev-as-detail-head h4{margin:0;color:var(--ev-as-green-900);font-size:1.15rem;font-weight:950}.ev-as-detail-head p{margin:5px 0 0;color:var(--ev-as-muted);font-size:.82rem}.ev-as-detail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.ev-as-detail-box,.ev-as-section{border:1px solid #E8EDF3;border-radius:16px;background:#fff;padding:11px 12px}.ev-as-detail-box span{display:block;color:var(--ev-as-muted);font-size:.7rem;font-weight:850;margin-bottom:3px}.ev-as-detail-box strong{display:block;color:var(--ev-as-text);font-size:.84rem;overflow-wrap:anywhere}.ev-as-section h6{margin:0 0 6px;color:var(--ev-as-green-900);font-size:.8rem;font-weight:950}.ev-as-section p{margin:0;color:#475569;font-size:.84rem;line-height:1.48;white-space:pre-wrap}.ev-as-files{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px}.ev-as-file{display:inline-flex;align-items:center;gap:6px;border:1px solid #DDE5ED;border-radius:999px;padding:6px 9px;background:#F8FAFC;color:#334155;text-decoration:none;font-size:.72rem;font-weight:850}.ev-as-file:hover{color:var(--ev-as-orange-dark);border-color:#FDBA74}.ev-as-timeline{display:grid;gap:8px;max-height:280px;overflow:auto}.ev-as-event{border-left:3px solid rgba(22,163,74,.3);padding:7px 9px;background:#F8FAFC;border-radius:0 12px 12px 0}.ev-as-event strong{display:block;color:#334155;font-size:.76rem}.ev-as-event p{font-size:.78rem;margin:2px 0;color:#64748B}.ev-as-event time{font-size:.68rem;color:#94A3B8}
.ev-as-resolve-form{display:grid;gap:10px;text-align:left}.ev-as-resolve-form label{font-size:.8rem;font-weight:900;color:#334155}.ev-as-resolve-form select,.ev-as-resolve-form textarea{border:1px solid #DCE4EE;border-radius:13px;padding:10px 11px;font-size:.87rem;outline:0}.ev-as-resolve-form textarea{min-height:110px;resize:vertical}.ev-as-resolve-note{padding:10px 12px;border-radius:14px;background:var(--ev-as-orange-050);border:1px solid #FED7AA;color:#9A3412;font-size:.8rem;line-height:1.45}
.ev-as-swal{border-radius:27px!important;border:1px solid #E5E7EB!important;box-shadow:0 30px 80px rgba(15,23,42,.23)!important}.ev-as-swal-title{color:var(--ev-as-green-900)!important;font-weight:950!important}.ev-as-swal-confirm{background:linear-gradient(135deg,var(--ev-as-orange),#F59E0B)!important;border:0!important;border-radius:14px!important;padding:11px 19px!important;font-weight:900!important}.ev-as-swal-cancel{background:#fff!important;color:#475569!important;border:1px solid #D1D5DB!important;border-radius:14px!important;padding:11px 19px!important;font-weight:900!important}
@media(max-width:991.98px){.ev-as-summary{grid-template-columns:1fr}.ev-as-case{grid-template-columns:1fr}.ev-as-btn-detail{width:100%}.ev-as-filters{width:100%}.ev-as-search{flex:1}.ev-as-search input{min-width:0;width:100%}}
@media(max-width:767.98px){.ev-as-page{padding:10px 8px 22px}.ev-as-hero{align-items:flex-start;flex-direction:column;padding:15px}.ev-as-hero h2{font-size:1.65rem}.ev-as-refresh{width:100%}.ev-as-tabs{width:100%;border-radius:16px}.ev-as-tab{flex:1}.ev-as-search{width:100%}.ev-as-panel-head,.ev-as-panel-body{padding:14px}.ev-as-detail-grid{grid-template-columns:1fr}.ev-as-detail-head{grid-template-columns:1fr}.ev-as-detail-head img{width:100%;height:170px}}
</style>
